backend:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/backend/**"
          - "packages/openapi/**"

pwa:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/pwa/**"
          - "packages/openapi-client/**"

solver:
  - changed-files:
      - any-glob-to-any-file: "solver-plugins/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

infra:
  - changed-files:
      - any-glob-to-any-file:
          - "infra/**"
          - "**/Dockerfile"
          - "**/Dockerfile.dockerignore"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"
